services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $emailSender: '%app.email_sender%'
            string $emailRecipient: '%app.email_recipient%'
            string $aruodasUrlToCrawl: '%app.aruodas_url_to_crawl%'
            string $alioUrlToCrawl: '%app.alio_url_to_crawl%'

    _instanceof:
        App\Crawler\CrawlerInterface:
            tags: ['app.crawler']

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Command\CrawlAdvertsCommand:
        arguments:
            $crawlers: !tagged 'app.crawler'

parameters:
    app.email_sender: '%env(string:APP_EMAIL_SENDER)%'
    app.email_recipient: '%env(string:APP_EMAIL_RECIPIENT)%'
    app.aruodas_url_to_crawl: '%env(string:APP_ARUODAS_URL_TO_CRAWL)%'
    app.alio_url_to_crawl: '%env(string:APP_ALIO_URL_TO_CRAWL)%'
